version: '3'
services:
  aftasfront:
    build:
      context: ./AFTAS-ANGULAR
      dockerfile: Dockerfile
    image: aftasfront:v1
    container_name: aftasfront
    ports:
      - "4200:80"
    depends_on:
      - aftasbackend
  aftasbackend:
    image: aftasbackend:v1
    container_name: aftasbackend
    restart: on-failure
    build:
      context: ./AFTAS_NEW
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod